### PR TITLE
Feature/add patch

### PR DESCRIPTION
**Pull request by jamesburton**
An update to add support for PATCH requests.

### CODE REVIEW

**Review by Burgyn — APPROVED** [review]

**Review by Burgyn — CHANGES_REQUESTED** [review]
Build failed. Please fix it.

**Comment by jamesburton** [comment]
I've updated the demo project to 6.0 as 5.0 is out of support now, but I get a successful build with all tests passing so I'm not sure why the source generator failed and left the demo project failing here ... hopefully this nudges it, but nothing obvious in the error messages.

**Review by Burgyn — APPROVED** [review]

**Comment by Burgyn** [comment]
Hi @jamesburton,
Thanks a lot. Your changes will be released as `v1.2.0` soon.

**Comment by jamesburton** [comment]
Cheers, it helps to keep the project current so people don't discount it immediately, and I think some tweaks to allow skiing the constructor and changing the base class may be simpler tweaks to continue with.
There are other options I can think of that may be useful, such as configuring View Model to Message mapping, perhaps via AutoMapper. Would you be interested in this being expanded to include such options, or prefer to see a separate project for that?

**Comment by Burgyn** [comment]
Hi. sorry for being so late but I was enjoying my time off.

Yes, I am interested in improving the project. I personally do not use AutoMapper, but I prefer to use Mapster. So it would be ideal if it were configured. But in principle, it does not matter even if it is linked directly to AutoMapper.

**Pull request merged**
